name: "Terraform-Applying Infrastructure"

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: | 
          terraform --version
          terraform fmt
        continue-on-error: true             
      - name: Terraform Init
        id: init
        run: terraform init             
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false
      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve
        continue-on-error: false
              
          
