name: "Terraform-Planning- Infrastructure"

on:
  push:
    branches:
      - developement

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: | 
          terraform --version
          terraform fmt
        continue-on-error: true
        #working-directory: ./terraform/vpc/environment/dev         
      - name: Terraform Init
        id: init
        run: terraform init
              
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        